name: Latest book list from a goodreads
on:
  schedule: # Run workflow automatically
    # This will make it run every Sunday morning 1 AM
    - cron: "0 1 * * 0"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with goodreads books
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@v1.2.3
        with:
          goodreads_user_id: "84989642"
          shelf: "read"
          max_books_count: "5"
          readme_file_path: "./README.md"
          sort_by_fields: ">user_read_at"
          template: "- [$title]($url) by $author ($my_rating_stars)"
